"""Auto-generated by c_struct_to_ctypes.py
Reference:
1) https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/studio.h
2) https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/optimize.h
"""
import ctypes
from gmod.custom_structure import PrintableStruct

byte = ctypes.c_ubyte


class Vector(PrintableStruct):
    _fields_ = (
        ("x", ctypes.c_float),
        ("y", ctypes.c_float),
        ("z", ctypes.c_float),
    )
    _pack_ = 1


class studiohdr_t(PrintableStruct):
    _fields_ = (
        ("id", ctypes.c_int),
        ("version", ctypes.c_int),
        ("checksum", ctypes.c_int),
        ("name", ctypes.c_char * 64),
        ("dataLength", ctypes.c_int),
        ("eyeposition", Vector),
        ("illumposition", Vector),
        ("hull_min", Vector),
        ("hull_max", Vector),
        ("view_bbmin", Vector),
        ("view_bbmax", Vector),
        ("flags", ctypes.c_int),
        ("bone_count", ctypes.c_int),
        ("bone_offset", ctypes.c_int),
        ("bonecontroller_count", ctypes.c_int),
        ("bonecontroller_offset", ctypes.c_int),
        ("hitbox_count", ctypes.c_int),
        ("hitbox_offset", ctypes.c_int),
        ("localanim_count", ctypes.c_int),
        ("localanim_offset", ctypes.c_int),
        ("localseq_count", ctypes.c_int),
        ("localseq_offset", ctypes.c_int),
        ("activitylistversion", ctypes.c_int),
        ("eventsindexed", ctypes.c_int),
        ("texture_count", ctypes.c_int),
        ("texture_offset", ctypes.c_int),
        ("texturedir_count", ctypes.c_int),
        ("texturedir_offset", ctypes.c_int),
        ("skinreference_count", ctypes.c_int),
        ("skinrfamily_count", ctypes.c_int),
        ("skinreference_index", ctypes.c_int),
        ("bodypart_count", ctypes.c_int),
        ("bodypart_offset", ctypes.c_int),
        ("attachment_count", ctypes.c_int),
        ("attachment_offset", ctypes.c_int),
        ("localnode_count", ctypes.c_int),
        ("localnode_index", ctypes.c_int),
        ("localnode_name_index", ctypes.c_int),
        ("flexdesc_count", ctypes.c_int),
        ("flexdesc_index", ctypes.c_int),
        ("flexcontroller_count", ctypes.c_int),
        ("flexcontroller_index", ctypes.c_int),
        ("flexrules_count", ctypes.c_int),
        ("flexrules_index", ctypes.c_int),
        ("ikchain_count", ctypes.c_int),
        ("ikchain_index", ctypes.c_int),
        ("mouths_count", ctypes.c_int),
        ("mouths_index", ctypes.c_int),
        ("localposeparam_count", ctypes.c_int),
        ("localposeparam_index", ctypes.c_int),
        ("surfaceprop_index", ctypes.c_int),
        ("keyvalue_index", ctypes.c_int),
        ("keyvalue_count", ctypes.c_int),
        ("iklock_count", ctypes.c_int),
        ("iklock_index", ctypes.c_int),
        ("mass", ctypes.c_float),
        ("contents", ctypes.c_int),
        ("includemodel_count", ctypes.c_int),
        ("includemodel_index", ctypes.c_int),
        ("virtualModel", ctypes.c_int),
        ("animblocks_name_index", ctypes.c_int),
        ("animblocks_count", ctypes.c_int),
        ("animblocks_index", ctypes.c_int),
        ("animblockModel", ctypes.c_int),
        ("bonetablename_index", ctypes.c_int),
        ("vertex_base", ctypes.c_int),
        ("offset_base", ctypes.c_int),
        ("directionaldotproduct", byte),
        ("rootLod", byte),
        ("numAllowedRootLods", byte),
        ("unused0", byte),
        ("unused1", ctypes.c_int),
        ("flexcontrollerui_count", ctypes.c_int),
        ("flexcontrollerui_index", ctypes.c_int),
        ("vertAnimFixedPointScale", ctypes.c_float),
        ("unused2", ctypes.c_int),
        ("studiohdr2index", ctypes.c_int),
        ("unused3", ctypes.c_int),
    )
    _pack_ = 1


class studiohdr2_t(PrintableStruct):
    _fields_ = (
        ("srcbonetransform_count", ctypes.c_int),
        ("srcbonetransform_index", ctypes.c_int),
        ("illumpositionattachmentindex", ctypes.c_int),
        ("flMaxEyeDeflection", ctypes.c_float),
        ("linearbone_index", ctypes.c_int),
        ("unknown", ctypes.c_int * 64),
    )
    _pack_ = 1


class mstudiotexture_t(PrintableStruct):
    _fields_ = (
        ("name_offset", ctypes.c_int),
        ("flags", ctypes.c_int),
        ("used", ctypes.c_int),
        ("unused", ctypes.c_int),
        ("material", ctypes.c_int),
        ("client_material", ctypes.c_int),
        ("unused2", ctypes.c_int * 10),
    )
    _pack_ = 1


class mstudio_modelvertexdata_t(PrintableStruct):
    _fields_ = (
        ("pVertexData", ctypes.c_int),
        ("pTangentData", ctypes.c_int),
    )
    _pack_ = 1


class mstudio_meshvertexdata_t(PrintableStruct):
    _fields_ = (
        ("modelvertexdata", ctypes.c_int),
        ("numLODVertexes", ctypes.c_int * 8),
    )
    _pack_ = 1


class mstudiomodel_t(PrintableStruct):
    _fields_ = (
        ("name", ctypes.c_char * 64),
        ("type", ctypes.c_int),
        ("boundingradius", ctypes.c_float),
        ("nummeshes", ctypes.c_int),
        ("meshindex", ctypes.c_int),
        ("numvertices", ctypes.c_int),
        ("vertexindex", ctypes.c_int),
        ("tangentsindex", ctypes.c_int),
        ("numattachments", ctypes.c_int),
        ("attachmentindex", ctypes.c_int),
        ("numeyeballs", ctypes.c_int),
        ("eyeballindex", ctypes.c_int),
        ("vertexdata", mstudio_modelvertexdata_t),
        ("unused", ctypes.c_int * 8),
    )
    _pack_ = 1


class mstudiomesh_t(PrintableStruct):
    _fields_ = (
        ("material", ctypes.c_int),
        ("modelindex", ctypes.c_int),
        ("numvertices", ctypes.c_int),
        ("vertexoffset", ctypes.c_int),
        ("numflexes", ctypes.c_int),
        ("flexindex", ctypes.c_int),
        ("materialtype", ctypes.c_int),
        ("materialparam", ctypes.c_int),
        ("meshid", ctypes.c_int),
        ("center", Vector),
        ("vertexdata", mstudio_meshvertexdata_t),
        ("unused", ctypes.c_int * 8),
    )
    _pack_ = 1


class mstudiohitboxset_t(PrintableStruct):
    _fields_ = (
        ("sznameindex", ctypes.c_int),
        ("numhitboxes", ctypes.c_int),
        ("hitboxindex", ctypes.c_int),
    )
    _pack_ = 1


class mstudiobodyparts_t(PrintableStruct):
    _fields_ = (
        ("sznameindex", ctypes.c_int),
        ("nummodels", ctypes.c_int),
        ("base", ctypes.c_int),
        ("modelindex", ctypes.c_int),
    )
    _pack_ = 1


class Quaternion(PrintableStruct):
    _fields_ = (
        ("x", ctypes.c_float),
        ("y", ctypes.c_float),
        ("z", ctypes.c_float),
        ("w", ctypes.c_float),
    )
    _pack_ = 1


class RadianEuler(PrintableStruct):
    _fields_ = (
        ("x", ctypes.c_float),
        ("y", ctypes.c_float),
        ("z", ctypes.c_float),
    )
    _pack_ = 1


class matrix3x4_t(PrintableStruct):
    _fields_ = (
        ("m_flMatVal", ctypes.c_float * 12),
    )
    _pack_ = 1


class mstudiobone_t(PrintableStruct):
    _fields_ = (
        ("sznameindex", ctypes.c_int),
        ("parent", ctypes.c_int),
        ("bonecontroller", ctypes.c_int * 6),
        ("pos", Vector),
        ("quat", Quaternion),
        ("rot", RadianEuler),
        ("posscale", Vector),
        ("rotscale", Vector),
        ("poseToBone", matrix3x4_t),
        ("qAlignment", Quaternion),
        ("flags", ctypes.c_int),
        ("proctype", ctypes.c_int),
        ("procindex", ctypes.c_int),
        ("physicsbone", ctypes.c_int),
        ("surfacepropidx", ctypes.c_int),
        ("contents", ctypes.c_int),
        ("unused", ctypes.c_int * 8),
    )
    _pack_ = 1


class vertexFileHeader_t(PrintableStruct):
    _fields_ = (
        ("id", ctypes.c_int),
        ("version", ctypes.c_int),
        ("checksum", ctypes.c_int),
        ("numLODs", ctypes.c_int),
        ("numLODVertexes", ctypes.c_int * 8),
        ("numFixups", ctypes.c_int),
        ("fixupTableStart", ctypes.c_int),
        ("vertexDataStart", ctypes.c_int),
        ("tangentDataStart", ctypes.c_int),
    )
    _pack_ = 1


class mstudioboneweight_t(PrintableStruct):
    _fields_ = (
        ("weight", ctypes.c_float * 3),
        ("bone", ctypes.c_char * 3),
        ("numbones", byte),
    )
    _pack_ = 1


class Vector2D(PrintableStruct):
    _fields_ = (
        ("x", ctypes.c_float),
        ("y", ctypes.c_float),
    )
    _pack_ = 1


class mstudiovertex_t(PrintableStruct):
    _fields_ = (
        ("m_BoneWeights", mstudioboneweight_t),
        ("m_vecPosition", Vector),
        ("m_vecNormal", Vector),
        ("m_vecTexCoord", Vector2D),
    )
    _pack_ = 1


class FileHeader_t(PrintableStruct):
    _fields_ = (
        ("version", ctypes.c_int),
        ("vertCacheSize", ctypes.c_int),
        ("maxBonesPerStrip", ctypes.c_ushort),
        ("maxBonesPerTri", ctypes.c_ushort),
        ("maxBonesPerVert", ctypes.c_int),
        ("checkSum", ctypes.c_int),
        ("numLODs", ctypes.c_int),
        ("materialReplacementListOffset", ctypes.c_int),
        ("numBodyParts", ctypes.c_int),
        ("bodyPartOffset", ctypes.c_int),
    )
    _pack_ = 1


class BodyPartHeader_t(PrintableStruct):
    _fields_ = (
        ("numModels", ctypes.c_int),
        ("modelOffset", ctypes.c_int),
    )
    _pack_ = 1


class ModelHeader_t(PrintableStruct):
    _fields_ = (
        ("numLODs", ctypes.c_int),
        ("lodOffset", ctypes.c_int),
    )
    _pack_ = 1


class ModelLODHeader_t(PrintableStruct):
    _fields_ = (
        ("numMeshes", ctypes.c_int),
        ("meshOffset", ctypes.c_int),
        ("switchPoint", ctypes.c_float),
    )
    _pack_ = 1


class MeshHeader_t(PrintableStruct):
    _fields_ = (
        ("numStripGroups", ctypes.c_int),
        ("stripGroupHeaderOffset", ctypes.c_int),
        ("flags", ctypes.c_ubyte),
    )
    _pack_ = 1


class StripGroupHeader_t(PrintableStruct):
    _fields_ = (
        ("numVerts", ctypes.c_int),
        ("vertOffset", ctypes.c_int),
        ("numIndices", ctypes.c_int),
        ("indexOffset", ctypes.c_int),
        ("numStrips", ctypes.c_int),
        ("stripOffset", ctypes.c_int),
        ("flags", ctypes.c_ubyte),
    )
    _pack_ = 1


class StripHeader_t(PrintableStruct):
    _fields_ = (
        ("numIndices", ctypes.c_int),
        ("indexOffset", ctypes.c_int),
        ("numVerts", ctypes.c_int),
        ("vertOffset", ctypes.c_int),
        ("numBones", ctypes.c_short),
        ("flags", ctypes.c_ubyte),
        ("numBoneStateChanges", ctypes.c_int),
        ("boneStateChangeOffset", ctypes.c_int),
    )
    _pack_ = 1


class Vertex_t(PrintableStruct):
    _fields_ = (
        ("boneWeightIndex", ctypes.c_ubyte * 3),
        ("numBones", ctypes.c_ubyte),
        ("origMeshVertID", ctypes.c_ushort),
        ("boneID", ctypes.c_char * 3),
    )
    _pack_ = 1


class mstudiobbox_t(PrintableStruct):
    _fields_ = (
        ("bone", ctypes.c_int),
        ("group", ctypes.c_int),
        ("bbmin", Vector),
        ("bbmax", Vector),
        ("szhitboxnameindex", ctypes.c_int),
        ("unused", ctypes.c_int * 8),
    )
    _pack_ = 1


class mstudioanimdesc_t(PrintableStruct):
    _fields_ = (
        ("baseptr", ctypes.c_int),
        ("sznameindex", ctypes.c_int),
        ("fps", ctypes.c_float),
        ("flags", ctypes.c_int),
        ("numframes", ctypes.c_int),
        ("nummovements", ctypes.c_int),
        ("movementindex", ctypes.c_int),
        ("unused1", ctypes.c_int * 6),
        ("animblock", ctypes.c_int),
        ("animindex", ctypes.c_int),
        ("numikrules", ctypes.c_int),
        ("ikruleindex", ctypes.c_int),
        ("animblockikruleindex", ctypes.c_int),
        ("numlocalhierarchy", ctypes.c_int),
        ("localhierarchyindex", ctypes.c_int),
        ("sectionindex", ctypes.c_int),
        ("sectionframes", ctypes.c_int),
        ("zeroframespan", ctypes.c_short),
        ("zeroframecount", ctypes.c_short),
        ("zeroframeindex", ctypes.c_int),
        ("zeroframestalltime", ctypes.c_float),
    )
    _pack_ = 1


class mstudioseqdesc_t(PrintableStruct):
    _fields_ = (
        ("baseptr", ctypes.c_int),
        ("szlabelindex", ctypes.c_int),
        ("szactivitynameindex", ctypes.c_int),
        ("flags", ctypes.c_int),
        ("activity", ctypes.c_int),
        ("actweight", ctypes.c_int),
        ("numevents", ctypes.c_int),
        ("eventindex", ctypes.c_int),
        ("bbmin", Vector),
        ("bbmax", Vector),
        ("numblends", ctypes.c_int),
        ("animindexindex", ctypes.c_int),
        ("movementindex", ctypes.c_int),
        ("groupsize", ctypes.c_int * 2),
        ("paramindex", ctypes.c_int * 2),
        ("paramstart", ctypes.c_float * 2),
        ("paramend", ctypes.c_float * 2),
        ("paramparent", ctypes.c_int),
        ("fadeintime", ctypes.c_float),
        ("fadeouttime", ctypes.c_float),
        ("localentrynode", ctypes.c_int),
        ("localexitnode", ctypes.c_int),
        ("nodeflags", ctypes.c_int),
        ("entryphase", ctypes.c_float),
        ("exitphase", ctypes.c_float),
        ("lastframe", ctypes.c_float),
        ("nextseq", ctypes.c_int),
        ("pose", ctypes.c_int),
        ("numikrules", ctypes.c_int),
        ("numautolayers", ctypes.c_int),
        ("autolayerindex", ctypes.c_int),
        ("weightlistindex", ctypes.c_int),
        ("posekeyindex", ctypes.c_int),
        ("numiklocks", ctypes.c_int),
        ("iklockindex", ctypes.c_int),
        ("keyvalueindex", ctypes.c_int),
        ("keyvaluesize", ctypes.c_int),
        ("cycleposeindex", ctypes.c_int),
        ("unused", ctypes.c_int * 7),
    )
    _pack_ = 1


class MaterialReplacementHeader_t(PrintableStruct):
    _fields_ = (
        ("materialID", ctypes.c_short),
        ("replacementMaterialNameOffset", ctypes.c_int),
    )
    _pack_ = 1


class MaterialReplacementListHeader_t(PrintableStruct):
    _fields_ = (
        ("numReplacements", ctypes.c_int),
        ("replacementOffset", ctypes.c_int),
    )
    _pack_ = 1


class vertexFileFixup_t(PrintableStruct):
    _fields_ = (
        ("lod", ctypes.c_int),
        ("sourceVertexID", ctypes.c_int),
        ("numVertexes", ctypes.c_int),
    )
    _pack_ = 1


